[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; 允许通过USB转串口或ST-Link下载
; upload_protocol = serial
upload_protocol = stlink ; (如果你手头有ST-Link V2下载器，请取消这行注释，并注释掉上面那行)

; 串口监视器波特率设置
monitor_speed = 115200
; 开启输入框，按回车发送
monitor_filters = send_on_enter

; 终极物理环境破壁方案：允许国产兼容版芯片烧录 (忽略非原版 ST 芯片的 IDCODE 检查)
upload_flags = -c set CPUTAPID 0x2ba01477

[env:native]
platform = native
test_framework = unity

lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit MPU6050 @ ^2.2.6
    SPI
    Wire
